[project]
name = "d2l-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "d2l>=1.0.3",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]
